# Generated by Django 4.0 on 2022-01-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('Netflix', models.BooleanField(default=False)),
                ('Amazon_Prime', models.BooleanField(default=False)),
                ('Spotify', models.BooleanField(default=False)),
                ('Apple_Music', models.BooleanField(default=False)),
                ('Hulu', models.BooleanField(default=False)),
                ('Costco', models.BooleanField(default=False)),
                ('HBO', models.BooleanField(default=False)),
                ('Youtube_Premium', models.BooleanField(default=False)),
                ('Disney_Plus', models.BooleanField(default=False)),
                ('iCloud', models.BooleanField(default=False)),
                ('Google_Drive', models.BooleanField(default=False)),
                ('OneDrive', models.BooleanField(default=False)),
                ('Dropbox', models.BooleanField(default=False)),
            ],
        ),
    ]
